"""
simple lil test script to verify the `action-values` endpoint
"""
import requests
import json

body = json.loads('''{
    "level_bundle": {
      "level": {
        "mobs": [
          {
            "max_lvl": 7,
            "pos": 1175,
            "HP": 4,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Snake",
            "time": 0,
            "id": 5,
            "buffs": [],
            "state": "SLEEPING",
            "HT": 4,
            "seen": false,
            "target": -1
          },
          {
            "max_lvl": 5,
            "pos": 731,
            "HP": 8,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Rat",
            "time": 0,
            "id": 6,
            "buffs": [],
            "state": "SLEEPING",
            "HT": 8,
            "seen": false,
            "target": -1
          },
          {
            "max_lvl": 5,
            "pos": 1140,
            "HP": 8,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Rat",
            "time": 0,
            "id": 7,
            "buffs": [],
            "state": "SLEEPING",
            "HT": 8,
            "seen": false,
            "target": -1
          },
          {
            "max_lvl": 7,
            "pos": 400,
            "HP": 4,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Snake",
            "time": 0,
            "id": 8,
            "buffs": [],
            "state": "SLEEPING",
            "HT": 4,
            "seen": false,
            "target": -1
          },
          {
            "max_lvl": 5,
            "pos": 860,
            "HP": 8,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Rat",
            "time": 0,
            "id": 9,
            "buffs": [],
            "state": "SLEEPING",
            "HT": 8,
            "seen": false,
            "target": -1
          },
          {
            "max_lvl": 5,
            "pos": 510,
            "HP": 8,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Rat",
            "time": 0,
            "id": 10,
            "buffs": [],
            "state": "SLEEPING",
            "HT": 8,
            "seen": false,
            "target": -1
          },
          {
            "max_lvl": 5,
            "pos": 1090,
            "HP": 15,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Albino",
            "time": 0,
            "id": 11,
            "buffs": [],
            "state": "SLEEPING",
            "HT": 15,
            "seen": false,
            "target": -1
          },
          {
            "max_lvl": 5,
            "pos": 1043,
            "HP": 8,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Rat",
            "time": 0,
            "id": 12,
            "buffs": [],
            "state": "SLEEPING",
            "HT": 8,
            "seen": false,
            "target": -1
          }
        ],
        "blobs": [],
        "mobs_to_spawn": [],
        "rooms": [
          {
            "top": 14,
            "left": 30,
            "bottom": 19,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.connection.TunnelRoom",
            "right": 33
          },
          {
            "top": 16,
            "left": 12,
            "bottom": 21,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.LibraryRoom",
            "right": 18,
            "entrance": {
              "x": 14,
              "y": 16,
              "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.Room$Door",
              "type_locked": false,
              "type": "LOCKED"
            }
          },
          {
            "top": 30,
            "left": 16,
            "bottom": 37,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.standard.exit.ExitRoom",
            "right": 21
          },
          {
            "top": 8,
            "left": 24,
            "bottom": 14,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.standard.entrance.EntranceRoom",
            "right": 33
          },
          {
            "top": 24,
            "left": 9,
            "bottom": 29,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.connection.RingTunnelRoom",
            "right": 16
          },
          {
            "top": 21,
            "left": 1,
            "bottom": 29,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.connection.TunnelRoom",
            "right": 9
          },
          {
            "top": 22,
            "left": 16,
            "bottom": 26,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.standard.WaterBridgeRoom",
            "right": 21
          },
          {
            "top": 6,
            "left": 12,
            "bottom": 16,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.standard.StudyRoom",
            "right": 24
          },
          {
            "top": 32,
            "left": 8,
            "bottom": 40,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.connection.TunnelRoom",
            "right": 16
          },
          {
            "top": 29,
            "left": 1,
            "bottom": 38,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.standard.WaterBridgeRoom",
            "right": 8
          },
          {
            "top": 1,
            "left": 24,
            "bottom": 8,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.connection.TunnelRoom",
            "right": 32
          },
          {
            "top": 14,
            "left": 7,
            "bottom": 21,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.connection.RingTunnelRoom",
            "right": 12
          },
          {
            "top": 19,
            "left": 26,
            "bottom": 26,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.standard.SewerPipeRoom",
            "right": 33
          },
          {
            "top": 26,
            "left": 21,
            "bottom": 32,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.standard.EmptyRoom",
            "right": 29
          }
        ],
        "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.SewerLevel",
        "customWalls": [],
        "feeling": "NONE",
        "transitions": [
          {
            "dest_depth": 0,
            "top": 12,
            "left": 29,
            "bottom": 12,
            "center": 449,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.features.LevelTransition",
            "right": 29,
            "dest_branch": 0,
            "type": "SURFACE"
          },
          {
            "dest_depth": 2,
            "top": 35,
            "left": 19,
            "dest_type": "REGULAR_ENTRANCE",
            "bottom": 35,
            "center": 1244,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.features.LevelTransition",
            "right": 19,
            "dest_branch": 0,
            "type": "REGULAR_EXIT"
          }
        ],
        "version": 833,
        "heaps": [
          {
            "haunted": false,
            "pos": 644,
            "auto_explored": false,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.Heap",
            "type": "HEAP",
            "items": [
              {
                "cursedKnown": false,
                "quantity": 1,
                "levelKnown": false,
                "cursed": false,
                "level": 0,
                "__className": "com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfIdentify",
                "kept_lost": false
              }
            ],
            "seen": false
          },
          {
            "haunted": false,
            "pos": 403,
            "auto_explored": false,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.Heap",
            "type": "HEAP",
            "items": [
              {
                "cursedKnown": false,
                "quantity": 1,
                "depth": 1,
                "levelKnown": false,
                "cursed": false,
                "level": 0,
                "__className": "com.shatteredpixel.shatteredpixeldungeon.items.keys.IronKey",
                "kept_lost": false
              }
            ],
            "seen": false
          },
          {
            "haunted": false,
            "pos": 1102,
            "auto_explored": false,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.Heap",
            "type": "HEAP",
            "items": [
              {
                "cursedKnown": false,
                "quantity": 1,
                "levelKnown": false,
                "cursed": false,
                "level": 0,
                "__className": "com.shatteredpixel.shatteredpixeldungeon.items.food.Pasty",
                "kept_lost": false
              }
            ],
            "seen": false
          },
          {
            "haunted": false,
            "pos": 1104,
            "auto_explored": false,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.Heap",
            "type": "HEAP",
            "items": [
              {
                "cursedKnown": false,
                "quantity": 1,
                "levelKnown": false,
                "cursed": false,
                "level": 0,
                "__className": "com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfParalyticGas",
                "kept_lost": false
              }
            ],
            "seen": false
          },
          {
            "haunted": false,
            "pos": 1172,
            "auto_explored": false,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.Heap",
            "type": "HEAP",
            "items": [
              {
                "cursedKnown": false,
                "quantity": 1,
                "levelKnown": false,
                "cursed": false,
                "level": 0,
                "__className": "com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfIntuition",
                "kept_lost": false
              }
            ],
            "seen": false
          },
          {
            "haunted": false,
            "pos": 1075,
            "auto_explored": false,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.Heap",
            "type": "HEAP",
            "items": [
              {
                "cursedKnown": false,
                "quantity": 63,
                "levelKnown": false,
                "cursed": false,
                "level": 0,
                "__className": "com.shatteredpixel.shatteredpixeldungeon.items.Gold",
                "kept_lost": false
              }
            ],
            "seen": false
          },
          {
            "haunted": false,
            "pos": 1266,
            "auto_explored": false,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.Heap",
            "type": "HEAP",
            "items": [
              {
                "cursedKnown": false,
                "quantity": 1,
                "levelKnown": false,
                "cursed": false,
                "level": 0,
                "__className": "com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfRecharging",
                "kept_lost": false
              }
            ],
            "seen": false
          },
          {
            "haunted": false,
            "pos": 716,
            "auto_explored": false,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.Heap",
            "type": "HEAP",
            "items": [
              {
                "cursedKnown": false,
                "quantity": 1,
                "levelKnown": false,
                "cursed": false,
                "level": 0,
                "__className": "com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfUpgrade",
                "kept_lost": false
              }
            ],
            "seen": false
          }
        ],
        "traps": [
          {
            "visible": true,
            "pos": 1277,
            "active": true,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.traps.WornDartTrap"
          },
          {
            "visible": true,
            "pos": 1088,
            "active": true,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.traps.WornDartTrap"
          },
          {
            "visible": true,
            "pos": 867,
            "active": true,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.levels.traps.WornDartTrap"
          }
        ],
        "plants": [],
        "width": 35,
        "visited": [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false
        ],
        "mapped": [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false
        ],
        "customTiles": [],
        "locked": false,
        "map": [
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 12, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 27, 27, 27, 27, 27, 27, 27, 27, 27, 14, 14, 5, 29, 29,
          29, 20, 20, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 27,
          14, 14, 14, 14, 14, 14, 14, 14, 14, 27, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 27, 14, 27, 27, 27, 14, 27,
          27, 27, 14, 27, 4, 1, 1, 20, 1, 1, 1, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 27, 14, 27, 14, 14, 14, 14, 14, 27, 14, 27, 4, 1, 1,
          1, 1, 1, 1, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 27, 14,
          14, 14, 14, 11, 14, 14, 14, 14, 14, 5, 1, 1, 1, 1, 1, 1, 1, 2, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 27, 14, 27, 14, 14, 14, 14, 14,
          27, 14, 27, 4, 1, 1, 1, 1, 7, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 27, 14, 27, 27, 27, 14, 27, 27, 27, 14, 27, 4, 1, 1, 1,
          1, 1, 1, 1, 20, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 27, 14,
          14, 14, 14, 14, 14, 14, 14, 14, 27, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 15, 5, 14, 14, 27, 27, 27, 27, 27,
          27, 27, 27, 27, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 15, 4, 4, 10, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 20, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 15, 15, 2, 4, 27, 14, 27,
          27, 27, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 12, 2, 4, 2, 4, 14, 14, 14, 14, 14, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 15, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 29, 2, 2, 1, 4,
          14, 14, 14, 14, 14, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 14, 14, 14, 14, 14, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 15, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 15, 15, 15, 15, 29,
          15, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 20, 4, 4, 4, 4, 4, 4, 4, 4, 4, 12,
          4, 4, 4, 4, 4, 4, 4, 4, 2, 29, 29, 29, 29, 15, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 1, 29, 29, 20, 4, 4, 4, 4, 4, 4, 1,
          29, 15, 15, 2, 15, 4, 4, 4, 4, 4, 4, 12, 12, 4, 4, 1, 4, 4, 4, 12, 12,
          12, 12, 4, 1, 14, 14, 1, 4, 4, 4, 4, 4, 4, 18, 29, 1, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 29, 29, 1, 1, 20, 4, 4, 1, 29, 29, 29, 29, 5, 1, 29, 29,
          20, 4, 4, 4, 4, 4, 4, 1, 1, 20, 4, 4, 4, 4, 4, 4, 4, 4, 4, 29, 4, 4,
          1, 4, 4, 4, 1, 4, 29, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 12, 4, 4, 4, 5, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 29, 4, 4, 1, 1, 20, 1, 1, 29, 29, 4, 4, 4,
          4, 4, 4, 4, 4, 29, 29, 29, 29, 29, 29, 29, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 29, 29, 29,
          29, 29, 29, 29, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 29, 29, 29, 1, 29, 29, 4, 4, 4, 4, 4,
          4, 4, 4, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          1, 29, 29, 29, 1, 29, 29, 4, 4, 4, 4, 4, 4, 4, 4, 1, 18, 1, 1, 1, 1,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 29, 1, 20, 1, 5, 1, 1, 1, 1, 1, 1, 20, 4,
          4, 4, 4, 4, 4, 4, 4, 29, 29, 29, 14, 29, 29, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 29, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 29,
          29, 29, 14, 29, 29, 4, 4, 4, 4, 4, 12, 4, 4, 4, 1, 1, 1, 20, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 29, 29, 29, 14, 29, 29, 4, 4,
          4, 4, 29, 29, 1, 1, 5, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 15, 2, 15, 1, 1, 1, 4, 4, 12, 12, 29, 4, 4, 4, 4, 1, 1, 8,
          20, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 15, 15, 2, 1, 1,
          1, 5, 29, 29, 29, 1, 4, 4, 4, 4, 18, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 15, 2, 1, 20, 1, 20, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4
        ],
        "height": 42,
        "respawner": {
          "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.mobs.MobSpawner",
          "time": 34,
          "id": 13
        }
      }
    },
    "game_bundle": {
      "seed_seed": -8443519510614474581,
      "secret_rooms": [
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretArtilleryRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretLibraryRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretSummoningRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretGardenRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretChestChasmRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretWellRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretLarderRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretHoneypotRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretHoardRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretRunestoneRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretMazeRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.secret.SecretLaboratoryRoom"
      ],
      "RingOfSharpshooting_label": "amethyst",
      "ScrollOfTransmutation_known": false,
      "PotionOfHaste_label": "bistre",
      "wep_t3_seed": 7033183046024058278,
      "placeholders": [],
      "mis_t2_seed": -3731509172244061804,
      "PotionOfInvisibility_known": false,
      "PotionOfHealing_label": "azure",
      "RingOfWealth_known": false,
      "branch": 0,
      "score": 0,
      "RingOfElements_label": "sapphire",
      "RingOfTenacity_label": "emerald",
      "ankhsUsed": 0,
      "foodEaten": 0,
      "RingOfArcana_label": "diamond",
      "energy": 0,
      "wep_t3_dropped": 0,
      "flr_expl1": false,
      "PotionOfToxicGas_label": "golden",
      "mis_t5_probs": [3, 3, 3],
      "version": 833,
      "wep_t5_seed": -6098265245574663950,
      "PotionOfLiquidFlame_known": false,
      "nextid": 14,
      "PotionOfFrost_known": false,
      "mis_t1_dropped": 0,
      "ScrollOfIdentify_label": "ODAL",
      "artifact_dropped": 0,
      "artifact_seed": -4570275127848466200,
      "amuletObtained": false,
      "seed": 2218740514485,
      "chapters": [],
      "ring_probs": [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
      "ScrollOfRecharging_label": "RAIDO",
      "wep_t3_probs": [2, 2, 2, 2, 2, 2],
      "seed_probs": [0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
      "gold": 0,
      "RingOfTenacity_known": false,
      "PotionOfHealing_known": true,
      "potion_probs": [0, 3, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1],
      "PotionOfExperience_label": "turquoise",
      "chal_mult": 1,
      "mis_t4_seed": 7717296953598434605,
      "wep_t2_probs": [2, 2, 2, 2, 2, 2, 0],
      "custom_seed": "",
      "wand_seed": 5229682806970666717,
      "qualifiedForNoKilling": true,
      "food_seed": 656026913606428512,
      "wep_t1_seed": -3521105078838333402,
      "region_secrets": [2, 2, 2, 3, 3],
      "ScrollOfLullaby_known": false,
      "scroll_dropped": 1,
      "PotionOfPurity_label": "crimson",
      "win_mult": 1,
      "wep_t1_probs": [2, 0, 2, 2, 2, 2],
      "ScrollOfRetribution_label": "BERKANAN",
      "won": false,
      "RingOfArcana_known": false,
      "ascended": false,
      "potion_seed": -1620191317375124795,
      "wep_t1_dropped": 0,
      "PotionOfInvisibility_label": "charcoal",
      "special_rooms": [
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.SentryRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.MagicalFireRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.PoolRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.GardenRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.StatueRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.TrapsRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.ArmoryRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.CrystalPathRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.CrystalChoiceRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.StorageRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.SacrificeRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.MagicWellRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.WeakFloorRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.ToxicGasRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.CrystalVaultRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.TreasuryRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.CryptRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.RunestoneRoom",
        "com.shatteredpixel.shatteredpixeldungeon.levels.rooms.special.LibraryRoom"
      ],
      "ScrollOfRecharging_known": false,
      "quests": {
        "blacksmith": { "spawned": false },
        "wandmaker": { "spawned": false },
        "sadGhost": { "spawned": false },
        "demon": { "spawned": false }
      },
      "stone_probs": [0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0],
      "PotionOfLevitation_label": "silver",
      "spawnersAlive": 0,
      "boss_scores": [0, 0, 0, 0, 0],
      "ScrollOfUpgrade_label": "NAUDIZ",
      "ScrollOfMirrorImage_label": "LAGUZ",
      "first_deck": false,
      "thrownAssists": 0,
      "mobs_to_champion": 0,
      "records": [],
      "mis_t5_seed": -1755345155055343840,
      "RingOfForce_known": false,
      "placements": [false, false, false, false, false, false],
      "duration": 16,
      "artifact_probs": [1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1],
      "ScrollOfLullaby_label": "TIWAZ",
      "general_probs": [
        0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 7, 1, 7, 1, 9
      ],
      "ring_seed": -6739457987256581691,
      "ScrollOfTerror_known": false,
      "RingOfEvasion_known": false,
      "ScrollOfTransmutation_label": "GYFU",
      "potionsCooked": 0,
      "ScrollOfMirrorImage_known": false,
      "PotionOfLiquidFlame_label": "ivory",
      "qualifiedForBossChallengeBadge": false,
      "mis_t4_dropped": 0,
      "daily_replay": false,
      "PotionOfLevitation_known": false,
      "PotionOfFrost_label": "magenta",
      "tot_quest": 0,
      "food_dropped": 1,
      "mis_t5_dropped": 0,
      "prog_score": 0,
      "expl_score": 0,
      "quest_scores": [0, 0, 0, 0, 0],
      "ScrollOfRemoveCurse_known": false,
      "ScrollOfTerror_label": "SOWILO",
      "mis_t3_seed": -383940745628352590,
      "RingOfEnergy_label": "onyx",
      "RingOfHaste_known": false,
      "mis_t2_probs": [3, 3, 3],
      "qualifiedForBossRemainsBadge": false,
      "wep_t2_seed": -7682752395165579470,
      "scroll_using_probs2": true,
      "RingOfForce_label": "quartz",
      "ScrollOfMagicMapping_label": "KAUNAN",
      "PotionOfParalyticGas_label": "amber",
      "PotionOfStrength_known": false,
      "priranhas": 0,
      "limited_drops": {
        "VELVET_POUCH": 1,
        "SCROLL_HOLDER": 0,
        "BAT_HP": 0,
        "GUARD_ARM": 0,
        "INT_STONE": 1,
        "POTION_BANDOLIER": 0,
        "LORE_CAVES": 0,
        "SWARM_HP": 0,
        "TRINKET_CATA": 0,
        "THEIF_MISC": 0,
        "LAB_ROOM": 0,
        "SLIME_WEP": 0,
        "WARLOCK_HP": 0,
        "ARCANE_STYLI": 0,
        "COOKING_HP": 0,
        "SHAMAN_WAND": 0,
        "LORE_PRISON": 0,
        "LORE_CITY": 0,
        "GOLEM_EQUIP": 0,
        "SKELE_WEP": 0,
        "BLANDFRUIT_SEED": 0,
        "MAGICAL_HOLSTER": 0,
        "LORE_SEWERS": 0,
        "NECRO_HP": 0,
        "LORE_HALLS": 0,
        "STRENGTH_POTIONS": 0,
        "DM200_EQUIP": 0,
        "UPGRADE_SCROLLS": 1,
        "ENCH_STONE": 0
      },
      "PotionOfMindVision_label": "indigo",
      "RingOfFuror_known": false,
      "PotionOfPurity_known": false,
      "mis_t1_probs": [3, 3, 3, 0],
      "stone_seed": 9105308946437311541,
      "RingOfEvasion_label": "agate",
      "last_played": 1755469161979,
      "wep_t4_dropped": 0,
      "total_score": 0,
      "wand_dropped": 0,
      "food_probs": [4, 0, 0],
      "ScrollOfRage_known": true,
      "ScrollOfRetribution_known": false,
      "ScrollOfRemoveCurse_label": "YNGVI",
      "mis_t1_seed": -805199665266698422,
      "upgradesUsed": 0,
      "ScrollOfUpgrade_known": false,
      "next_custom_id": 0,
      "trinket_seed": 34154500802800567,
      "enemiesSlain": 0,
      "maxDepth": 1,
      "mis_t2_dropped": 0,
      "depth": 1,
      "sneakAttacks": 0,
      "PotionOfParalyticGas_known": false,
      "wep_t4_seed": -5406648064283879167,
      "RingOfAccuracy_label": "tourmaline",
      "wand_probs": [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
      "PotionOfStrength_label": "jade",
      "RingOfAccuracy_known": false,
      "RingOfEnergy_known": false,
      "stone_dropped": 0,
      "PotionOfExperience_known": false,
      "RingOfHaste_label": "topaz",
      "PotionOfToxicGas_known": false,
      "mis_t3_probs": [3, 3, 3],
      "maxAscent": 0,
      "wep_t5_dropped": 0,
      "tres_score": 0,
      "RingOfElements_known": false,
      "wep_t4_probs": [2, 2, 2, 2, 2, 2, 2],
      "tot_boss": 0,
      "potion_dropped": 1,
      "PotionOfHaste_known": false,
      "mis_t3_dropped": 0,
      "daily": false,
      "scroll_seed": 7197642077397107584,
      "PotionOfMindVision_known": false,
      "ScrollOfRage_label": "ISAZ",
      "RingOfFuror_label": "garnet",
      "RingOfSharpshooting_known": false,
      "RingOfMight_known": false,
      "trinket_probs": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      "item_val": 0,
      "challenges": 0,
      "pit_needed": -1,
      "potion_using_probs2": false,
      "ScrollOfMagicMapping_known": false,
      "hero": {
        "htboost": 0,
        "cursed": false,
        "HP": 20,
        "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero",
        "HT": 20,
        "inventory": [
          {
            "spawned": false,
            "cursedKnown": false,
            "quantity": 3,
            "levelKnown": true,
            "cursed": false,
            "level": 0,
            "uses_left_to_id": 20,
            "quickslotpos": 0,
            "durability": 100,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.ThrowingStone",
            "kept_lost": false,
            "curse_infusion_bonus": false,
            "augment": "NONE",
            "mastery_potion_bonus": false,
            "available_uses": 10,
            "enchant_hardened": false
          },
          {
            "cursedKnown": false,
            "quantity": 1,
            "levelKnown": false,
            "cursed": false,
            "level": 0,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.food.Food",
            "kept_lost": false
          },
          {
            "volume": 0,
            "cursedKnown": false,
            "quantity": 1,
            "levelKnown": false,
            "cursed": false,
            "level": 0,
            "quickslotpos": 1,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.Waterskin",
            "kept_lost": false
          },
          {
            "cursedKnown": false,
            "quantity": 1,
            "levelKnown": false,
            "cursed": false,
            "level": 0,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.bags.VelvetPouch",
            "inventory": [],
            "kept_lost": false
          }
        ],
        "attackSkill": 10,
        "STR": 10,
        "weapon": {
          "cursedKnown": true,
          "quantity": 1,
          "levelKnown": true,
          "cursed": false,
          "level": 0,
          "uses_left_to_id": 20,
          "__className": "com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.WornShortsword",
          "kept_lost": false,
          "curse_infusion_bonus": false,
          "augment": "NONE",
          "mastery_potion_bonus": false,
          "available_uses": 10,
          "enchant_hardened": false
        },
        "pos": 302,
        "id": 1,
        "buffs": [
          {
            "partial_regen": 0,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Regeneration",
            "time": 0,
            "id": 2
          },
          {
            "level": 16,
            "partialDamage": 0,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Hunger",
            "time": 0,
            "id": 3
          },
          {
            "shielding": 0,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.BrokenSeal$WarriorShield",
            "time": 0,
            "id": 4
          }
        ],
        "replacements": {},
        "defenseSkill": 5,
        "exp": 0,
        "class": "WARRIOR",
        "cursedKnown": false,
        "lvl": 1,
        "quantity": 1,
        "levelKnown": false,
        "subClass": "NONE",
        "level": 0,
        "talents_tier_3": {},
        "talents_tier_4": {},
        "talents_tier_1": {},
        "talents_tier_2": {},
        "kept_lost": false,
        "armor": {
          "cursedKnown": true,
          "quantity": 1,
          "levelKnown": true,
          "cursed": false,
          "level": 0,
          "uses_left_to_id": 10,
          "seal": {
            "cursedKnown": true,
            "quantity": 1,
            "levelKnown": true,
            "cursed": false,
            "level": 0,
            "__className": "com.shatteredpixel.shatteredpixeldungeon.items.BrokenSeal",
            "kept_lost": false
          },
          "__className": "com.shatteredpixel.shatteredpixeldungeon.items.armor.ClothArmor",
          "kept_lost": false,
          "curse_infusion_bonus": false,
          "augment": "NONE",
          "glyph_hardened": false,
          "mastery_potion_bonus": false,
          "available_uses": 5
        },
        "time": 0
      },
      "ScrollOfTeleportation_known": false,
      "RingOfWealth_label": "ruby",
      "item_types_discovered": [
        "com.shatteredpixel.shatteredpixeldungeon.items.Waterskin",
        "com.shatteredpixel.shatteredpixeldungeon.items.armor.ClothArmor",
        "com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfHealing",
        "com.shatteredpixel.shatteredpixeldungeon.items.food.Food",
        "com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfIdentify",
        "com.shatteredpixel.shatteredpixeldungeon.items.bags.VelvetPouch",
        "com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.WornShortsword",
        "com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.ThrowingStone",
        "com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfRage"
      ],
      "ScrollOfTeleportation_label": "MANNAZ",
      "generated_levels": [1],
      "wep_t2_dropped": 0,
      "ScrollOfIdentify_known": true,
      "seed_dropped": 0,
      "ring_dropped": 0,
      "badges": { "badges": ["BAG_BOUGHT_VELVET_POUCH"] },
      "init_ver": 833,
      "trinket_dropped": 0,
      "scroll_probs": [0, 3, 2, 2, 0, 2, 1, 1, 1, 1, 1, 0],
      "RingOfMight_label": "opal",
      "mis_t4_probs": [3, 3, 3],
      "wep_t5_probs": [2, 2, 2, 2, 2, 2, 2]
    }
  }''')

print(requests.post("http://localhost:5000/action-values", json=body).text)